# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'RACDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RACDemo
pod 'ReactiveCocoa', '~> 2.5'

pod 'MBProgressHUD'

pod 'AFNetworking'

end
